/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2018-04-19 15:32:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class selectCourse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/c.tld", Long.valueOf(1524055671889L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("  \r\n");
      out.write("  \r\n");
  
String path = request.getContextPath();  
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";  

      out.write("  \r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">  \r\n");
      out.write("<html>  \r\n");
      out.write("  <head>  \r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">  \r\n");
      out.write("    <title>select courses</title> \r\n");
      out.write("    <script type=\"text/javascript\" src=\"jquery-3.3.1.min.js\"></script> \r\n");
      out.write("  </head>  \r\n");
      out.write("    \r\n");
      out.write("  <body style=\"text-align:center; margin-left:auto;margin-right:auto;\">  \r\n");
      out.write("  <div style=\"margin-top: 50px; \">\r\n");
      out.write("  \t<h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</h1> \r\n");
      out.write("  \t<div style=\"margin-top: 100px;\"> <span>name:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(", </span> <span>choose times: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${chance}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(", </span> <span>days:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${days}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span> </div>\r\n");
      out.write("  \t<div style=\"margin-top: 50px;\"> \r\n");
      out.write("  \t\t<p>you have choosed: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseStr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</p>\r\n");
      out.write("\t       ");
      out.write("\r\n");
      out.write("\t    \t now you can choose:<br/> \r\n");
      out.write("\t    \t ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t     <br/>\r\n");
      out.write("\t\t     <input id=\"confirm\" type=\"button\" value=\"confirm\" name=\"btn\"  style=\"margin-top: 20px;\"/> \r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t<hr style=\"margin-top:50px;\">\r\n");
      out.write("  \t<div style=\"margin-top:50px;\">\r\n");
      out.write("  \t\tplease charge:<br/> \r\n");
      out.write("  \t\t<input type=\"radio\" name=\"gender\" value=\"10\" style=\"margin-top: 20px;\">1000yuan,10 courses   <br />\r\n");
      out.write("\t\t<input type=\"radio\" name=\"gender\" value=\"20\" style=\"margin-top: 20px;\">1500yuan,20 courses\t<br />\r\n");
      out.write("\t\t<input type=\"radio\" name=\"gender\" value=\"30\" style=\"margin-top: 20px;\">2000yuan,30 courses\t<br />\r\n");
      out.write("  \t\t<input id=\"charge\" type=\"button\" value=\"charge\" name=\"btn\"  style=\"margin-top: 20px;\"/>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  </body>  \r\n");
      out.write("  <script>\r\n");
      out.write("  $(\"#confirm\").click(function() {\r\n");
      out.write("      courses = $(\"input:checkbox[name='mm']:checked\").map(function(index,elem) {\r\n");
      out.write("          return $(elem).val();\r\n");
      out.write("      }).get().join(',');\r\n");
      out.write("      \r\n");
      out.write("      $.ajax({      \r\n");
      out.write("    \t  type : \"POST\", //提交方式      \r\n");
      out.write("    \t  url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajaxSubmitCourse\",//路径   \r\n");
      out.write("    \t  dataType : \"text\", \r\n");
      out.write("    \t  data : {\"courses\" : courses,\r\n");
      out.write("    \t\t   \t  \"studentId\": '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("    \t\t   \t  \"studentName\": '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'\r\n");
      out.write("    \t  \t\t},//数据，这里使用的是Json格式进行传输       \r\n");
      out.write("    \t  \tsuccess : function(result) {//返回数据根据结果进行相应的处理       \r\n");
      out.write("    \t\t     alert(result);\r\n");
      out.write("    \t  \t}, \r\n");
      out.write("\t  \t\terror : function(xhr, status, errMsg)\r\n");
      out.write("\t        {\r\n");
      out.write("\t             alert(\"failed!\");\r\n");
      out.write("\t        }\r\n");
      out.write("    \t  });  \r\n");
      out.write("      \r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("  $(\"#charge\").click(function() {\r\n");
      out.write("\t  var chance = $('input:radio:checked').val();\r\n");
      out.write("\t  $.ajax({      \r\n");
      out.write("    \t  type : \"POST\", //提交方式      \r\n");
      out.write("    \t  url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajaxSubmitCourse\",//路径   \r\n");
      out.write("    \t  dataType : \"text\", \r\n");
      out.write("    \t  data : {\"chance\" : chance,\r\n");
      out.write("    \t\t   \t  \"studentId\": '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("    \t\t   \t  \"studentName\": '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'\r\n");
      out.write("    \t  \t\t},//数据，这里使用的是Json格式进行传输       \r\n");
      out.write("    \t  \tsuccess : function(result) {//返回数据根据结果进行相应的处理       \r\n");
      out.write("    \t\t     alert(result);\r\n");
      out.write("    \t  \t}, \r\n");
      out.write("\t  \t\terror : function(xhr, status, errMsg)\r\n");
      out.write("\t        {\r\n");
      out.write("\t             alert(\"failed!\");\r\n");
      out.write("\t        }\r\n");
      out.write("   \t  });  \r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("</html>  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /selectCourse.jsp(29,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("course");
    // /selectCourse.jsp(29,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/selectCourse.jsp(29,7) '${ableList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ableList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("       \t\t \t<input type=\"checkbox\" name=\"mm\" value=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("  style=\"margin-left: 40px\"/> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\r\n");
          out.write("       \t\t ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
